### ISSUE TITLE
Buffer distance restrictions

### ISSUE THREAD

**Issue by SamDrummond** [WaimakaririGeospatial/DrawMeasureWidget#8]
The buffer tool distance parameter is restricted to 100. If a user tries to increment higher it flags an alert as per the screenshot:

![image](https://cloud.githubusercontent.com/assets/4656969/8919775/5f64f0b4-3516-11e5-8e19-a02eb4b31421.png)

Issue:
This is not useful for users wanting to create measurements between 100m and 1km.

Workflow:

1. Open the draw measure widget
2. Select the buffer tool
3. Type 101 as the buffer distance parameter

Outcome:
Users should not be restricted in the value they choose to buffer.

**Comment by arunsebastian** [comment]
Removed the restrictions .Latest code update should fix this
